const Colors = Object.freeze({
  buttonPrimary: '#79ADDC',
  buttonPrimaryLight: '#86b5e0',
  selectedHighlightColor: '#94bde3',
  textboxBackground: '#95A2A8', //'rgba(188, 212, 222, 0.42)',
  standardFont: '#FEFDFF',
  tooltipFont: '#FEFDFF',
  headingFont: '#FEFDFF',
  menuIconFont: '#FEFDFF',
  dropdownSelectedColor: '#304352',
  dropdownSelectedBackground: '#FEFDFF',
  underlineColorHovered: '#D2CFD2',
  underlineColor: '#0D0106',
  underlineColorFocused: '#FEFDFF',
  accent: '#BCD4DE',
  offBackground: '#93a8ac',
  offBorder: '#dfdfdf',
  inactiveTab: '#4B5A66',
  activeTab: '#304352',
  hoverTab: '#3D4E5B',
  tabBorderColor: '#EEEEFF',
  menuIconBorder: '#FEFDFF',
});

export default Colors;
