const ColorsFieldConstants = Object.freeze({__proto__: null,
  min: 0,
  max: 6,
  Red: Object.freeze({__proto__: null,
    placeholder: 'Red',
    underlineColor: '#831929',
    hoveredUnderlineColor: '#C56473',
    focusedUnderlineColor: '#dca2ab',
  }),
  Green: Object.freeze({__proto__: null,
    placeholder: 'Green',
    underlineColor: '#2e4d07',
    hoveredUnderlineColor: '#6ebb10',
    focusedUnderlineColor: '#99ed32',
  }),
  Blue: Object.freeze({__proto__: null,
    placeholder: 'Blue',
    underlineColor: '#1031A7',
    hoveredUnderlineColor: '#8fa5f4',
    focusedUnderlineColor: '#bdcaf9',
  }),
  White: Object.freeze({__proto__: null,
    placeholder: 'White',
    underlineColor: '#dad3c1',
    hoveredUnderlineColor: '#edeae1',
    focusedUnderlineColor: '#ffffff',
  }),
});

export default ColorsFieldConstants;
